kind: Service
apiVersion: v1
metadata:
  name: zuul-gateway
  labels:
    k8s-app: zuul-gateway
    service: zuul
spec:
  ports:
    - name: tcp-8400-8400-c6xcp
      protocol: TCP
      port: 8400
      targetPort: 8400
      nodePort: 31461
  selector:
    k8s-app: zuul-gateway
    service: zuul
  type: NodePort
