server:
  port: 8400

spring:
  application:
    name: zuul-gateway

zuul:
  routes:
    matchmaking:
      path: /matchmaking/**
      serviceId: battleship-matchmaking
    battleship:
      path: /battleship/**
      serviceId: battleship-game

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://battleshipgame.tk:30761/eureka
    instance:
      hostname: localhost

